insert into T_COMMAND_C (CI_ID, C_COMMAND_ID, C_COMMAND_DATE, C_COMMAND_STATUS, C_USER_NAME)
values ('1','C_AEDFRF','2023-11-29','PROCESSED','User 1');
insert into T_COMMAND_C (CI_ID, C_COMMAND_ID, C_COMMAND_DATE, C_COMMAND_STATUS, C_USER_NAME)
values ('2','C_BRTYGE','2023-11-29','NEW','User 2');
insert into T_COMMAND_C (CI_ID, C_COMMAND_ID, C_COMMAND_DATE, C_COMMAND_STATUS, C_USER_NAME)
values ('3','FRTYDS','2023-11-29','NEW','User 2');

insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('1','Mascara ref-1234AF','MAKEUP',45,1,'1');
insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('2','Rouge ref-1234AD','MAKEUP',45,2,'1');
insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('3','Coffret Rouge','MAKEUP',60,2,'2');
insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('4','T-Shirt','CLOTHING',150.99,3,'2');
insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('5','Coffret rouge','MAKEUP',60,2,'3');
insert into T_COMMAND_ITEM_CI(CI_ID, CI_PRIODUCT_NAME, CI_PRODUCT_TYPE, CI_PRODUCT_UNIT_PRICE, CI_PRODUCT_QUANTITY, CI_C_COMMAND_ID)
values ('6','Mascara ref-1234AF','MAKEUP',60,3,'3');
