spring:
  application:
    name: demo
  datasource:
    url: jdbc:h2:mem:demo;MODE=ORacle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    dirverClassName: org.h2.Driver
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/demo-changelog.yml
    default-schema: public
  jpa:
    spring.jpa.database-playform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
server:
  port: 9001